save_dir: save/
model_name: VT5
model_weights: rubentito/vt5-base-spdocvqa
# model_weights: /data/shared/PFL-DocVQA/Checkpoints/vt5_sp-docvqa.ckpt
max_input_tokens: 512
device: cuda
seed: 42

visual_module:
  model: dit
  model_weights: /media/chs.gpu/19b31863-d2db-44c2-b407-9a4ffbebcbd1/DATA/PFL-DocVQA/models/vt5_base.ckpt/vm_model
  finetune: False

training_parameters:
  lr: 0.005  # 2e-4
  batch_size: 8
  lora_rank: 16
  # warmup_iterations: 1000

fl_parameters:
  sample_clients: 2
  total_clients: 10
  num_rounds: 30
  iterations_per_fl_round: 1

dp_parameters:
  providers_per_fl_round: 45
  sensitivity: 0.5  # [0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
  noise_multiplier: 1.21 # {1: 1.145, 4: 0.637, 8: 0.468}
  target_epsilon: 1

