dataset_name: PFL-DocVQA
imdb_dir: /media/chs.hdsi/DATA/PFL-DocVQA/data/clients
images_dir: /media/chs.hdsi/DATA/PFL-DocVQA/data/images
provider_docs: /media/chs.hdsi/DATA/PFL-DocVQA/data/clients/data_points.json
